name: main_l1_15_prio_g2
tasks:
- alias: L1_P25_Swish
  level: 1
  problem_id: 25
- alias: L1_P50_Conv2dStandard
  level: 1
  problem_id: 50
- alias: L1_P61_ConvTranspose3d
  level: 1
  problem_id: 61
- alias: L1_P82_DepthwiseConv2d
  level: 1
  problem_id: 82
