name: tmp_l2_p1_p30_20260718_222714
tasks:
  - alias: L2_P1_Auto
    level: 2
    problem_id: 1
  - alias: L2_P2_Auto
    level: 2
    problem_id: 2
  - alias: L2_P3_Auto
    level: 2
    problem_id: 3
  - alias: L2_P4_Auto
    level: 2
    problem_id: 4
  - alias: L2_P5_Auto
    level: 2
    problem_id: 5
  - alias: L2_P6_Auto
    level: 2
    problem_id: 6
  - alias: L2_P7_Auto
    level: 2
    problem_id: 7
  - alias: L2_P8_Auto
    level: 2
    problem_id: 8
  - alias: L2_P9_Auto
    level: 2
    problem_id: 9
  - alias: L2_P10_Auto
    level: 2
    problem_id: 10
  - alias: L2_P11_Auto
    level: 2
    problem_id: 11
  - alias: L2_P12_Auto
    level: 2
    problem_id: 12
  - alias: L2_P13_Auto
    level: 2
    problem_id: 13
  - alias: L2_P14_Auto
    level: 2
    problem_id: 14
  - alias: L2_P15_Auto
    level: 2
    problem_id: 15
  - alias: L2_P16_Auto
    level: 2
    problem_id: 16
  - alias: L2_P17_Auto
    level: 2
    problem_id: 17
  - alias: L2_P18_Auto
    level: 2
    problem_id: 18
  - alias: L2_P19_Auto
    level: 2
    problem_id: 19
  - alias: L2_P20_Auto
    level: 2
    problem_id: 20
  - alias: L2_P21_Auto
    level: 2
    problem_id: 21
  - alias: L2_P22_Auto
    level: 2
    problem_id: 22
  - alias: L2_P23_Auto
    level: 2
    problem_id: 23
  - alias: L2_P24_Auto
    level: 2
    problem_id: 24
  - alias: L2_P25_Auto
    level: 2
    problem_id: 25
  - alias: L2_P26_Auto
    level: 2
    problem_id: 26
  - alias: L2_P27_Auto
    level: 2
    problem_id: 27
  - alias: L2_P28_Auto
    level: 2
    problem_id: 28
  - alias: L2_P29_Auto
    level: 2
    problem_id: 29
  - alias: L2_P30_Auto
    level: 2
    problem_id: 30
