name: main_l1_15_prio_g3
tasks:
- alias: L1_P89_Cumsum
  level: 1
  problem_id: 89
- alias: L1_P95_CrossEntropyLoss
  level: 1
  problem_id: 95
- alias: L1_P97_ScaledDotProductAttention
  level: 1
  problem_id: 97
