name: main_l1_15_prio_g0
tasks:
- alias: L1_P40_LayerNorm
  level: 1
  problem_id: 40
- alias: L1_P42_MaxPool2d
  level: 1
  problem_id: 42
- alias: L1_P45_AvgPool2d
  level: 1
  problem_id: 45
- alias: L1_P47_SumReduction
  level: 1
  problem_id: 47
