name: main_l1_15_prio_g1
tasks:
- alias: L1_P1_SquareMatmul
  level: 1
  problem_id: 1
- alias: L1_P10_TensorMatmul3D
  level: 1
  problem_id: 10
- alias: L1_P20_LeakyReLU
  level: 1
  problem_id: 20
- alias: L1_P33_BatchNorm
  level: 1
  problem_id: 33
